version: 2
updates:
  # Check for Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "py-deps"

  # Check for GitHub Actions version updates
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "actions"
